# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd07cc1c818cba4868b17d6a678f0aa54b496e1fb770c126149d6ac57b380231bea5de3a18742f3a76ac9b1e913b6306199c3330dcf95cd034f1ea842c47497

test:
  secret_key_base: 9c261483869b66cb0feacd5a7583ee2f95959fa329ebc2f94155fe39b8ce423b2b6fb617f7cbcae36c76d0b9e6c9a40199898647b35d2d54ec10cf37b01eb6d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
